### ISSUE TITLE
Directum 5.5, утилита не распознает константу SYSREQ_USERS_IS_PASSWORD_POLICY

### ISSUE THREAD

**Issue by fforregs** [DirectumCompany/IsblCheck#1]
https://club.directum.ru/webhelp/directum/5.5/index.html?om_rekvizity_komponenty_polzovateli.htm
![image](https://user-images.githubusercontent.com/9361966/34864940-a1144470-f787-11e7-8bf6-c4e187fead80.png)

**Comment by gorodilov-directum** [comment]
Исправлено в версии 1.2.0 - константа добавлена
